name: Sync result.m3u to Jianguoyun

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload result.m3u to Jianguoyun
        run: |
          curl -T "output/result.m3u" \
            -u "${{ secrets.JY_USER }}:${{ secrets.JY_PASS }}" \
            "https://dav.jianguoyun.com/dav/github/result.m3u"
