name: Sync result.m3u to Jianguoyun

on:
  schedule:
    - cron: "0 */6 * * *"   # 每 6 小时上传一次
  workflow_dispatch:         # 支持手动运行

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload result.m3u to Jianguoyun
        run: |
          curl -T "output/result.m3u" \
            -u "${{ caianxun@outlook.com }}:${{ a4vfhnxq6cxvtwsj }}" \
            "https://dav.jianguoyun.com/dav/github/result.m3u"
